// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21/08/2024, 16:26:45
const configMerger = require("C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/plugins/**/*.{js,ts,mjs}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/composables/**/*.{js,ts,mjs}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/utils/**/*.{js,ts,mjs}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Inteli/Documents/GitHub/2024-2A-T08-EC07-G01/src/app/app.config.{js,ts,mjs}"] }));

module.exports = config
