services:
  healthcheck:
    build:
      context: ./health-check
      dockerfile: Dockerfile
    container_name: healthcheck
    ports:
      - "8008:8008"
    networks:
      - network


networks:
  network:
